version: '2'
services:
  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-4.4-latest
    ports:
      - "10051:10051"
    volumes:
      - ./zabbix/zbx_env/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts
      - ./zabbix/zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts
      - ./zabbix/zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules
      - ./zabbix/zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc
      - ./zabbix/zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys
      - ./zabbix/zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs
    links:
      - mysql-server:mysql-server
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    env_file:
      - ./zabbix/.env_db_mysql
      - ./zabbix/.env_srv
    user: root
    labels:
      com.zabbix.description: "Zabbix server with MySQL database support"
      com.zabbix.company: "Zabbix SIA"
      com.zabbix.component: "zabbix-server"
      com.zabbix.dbtype: "mysql"
      com.zabbix.os: "alpine"

  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql:alpine-4.4-latest
    ports:
      - "80:80"

    links:
      - mysql-server:mysql-server
      - zabbix-server:zabbix-server

    env_file:
      - ./zabbix/.env_db_mysql
      - ./zabbix/.env_web
    user: root
    labels:
      com.zabbix.description: "Zabbix frontend on Nginx web-server with MySQL database support"
      com.zabbix.company: "Zabbix SIA"
      com.zabbix.component: "zabbix-frontend"
      com.zabbix.webserver: "nginx"
      com.zabbix.dbtype: "mysql"
      com.zabbix.os: "apline"

  mysql-server:
    image: mysql:5.7
    command: [mysqld, --character-set-server=utf8, --collation-server=utf8_bin]
    env_file:
      - ./zabbix/.env_db_mysql
    user: root