version: "3"
services:
  ignite-1:
    image: "apacheignite/ignite:2.9.0"
    environment:
      CONFIG_URI: /config/ignite-config.xml
      IGNITE_QUIET: "false"
      OPTION_LIBS: ignite-rest-http, ignite-opencensus
      JVM_OPTS: "-server -Xms1g  -Xmx1g -XX:NewSize=512m -XX:SurvivorRatio=6 -XX:+AlwaysPreTouch
              -XX:+UseG1GC -XX:MaxGCPauseMillis=2000 -XX:GCTimeRatio=4 -XX:InitiatingHeapOccupancyPercent=30
              -XX:G1HeapRegionSize=8M -XX:ConcGCThreads=2 -XX:G1HeapWastePercent=10 -XX:+UseTLAB
              -XX:+ScavengeBeforeFullGC -XX:+DisableExplicitGC -Dcom.sun.management.jmxremote 
              -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false
               -Dcom.sun.management.jmxremote.port=49112 -Dcom.sun.management.jmxremote.rmi.port=49112 -Djava.rmi.server.hostname=ignite -Dcom.sun.management.jmxremote.ssl=false"
    volumes:
      - ./ignite/conf:/config
    ports:
     - "8083:8080"
     - "10800:10800"

  ignite-2:
    image: "apacheignite/ignite:2.9.0"
    environment:
      CONFIG_URI: /config/ignite-config.xml
      IGNITE_QUIET: "false"
      OPTION_LIBS: ignite-rest-http, ignite-opencensus
      JVM_OPTS: "-server -Xms1g  -Xmx1g -XX:NewSize=512m -XX:SurvivorRatio=6 -XX:+AlwaysPreTouch
              -XX:+UseG1GC -XX:MaxGCPauseMillis=2000 -XX:GCTimeRatio=4 -XX:InitiatingHeapOccupancyPercent=30
              -XX:G1HeapRegionSize=8M -XX:ConcGCThreads=2 -XX:G1HeapWastePercent=10 -XX:+UseTLAB
              -XX:+ScavengeBeforeFullGC -XX:+DisableExplicitGC -Dcom.sun.management.jmxremote 
              -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false
               -Dcom.sun.management.jmxremote.port=49112 -Dcom.sun.management.jmxremote.rmi.port=49112 -Djava.rmi.server.hostname=ignite -Dcom.sun.management.jmxremote.ssl=false"
    volumes:
      - ./ignite/conf:/config
    ports:
     - "8084:8080"
     - "10801:10800"

  ignite-3:
    image: "apacheignite/ignite:2.9.0"
    environment:
      CONFIG_URI: /config/ignite-config.xml
      IGNITE_QUIET: "false"
      OPTION_LIBS: ignite-rest-http, ignite-opencensus
      JVM_OPTS: "-server -Xms1g  -Xmx1g -XX:NewSize=512m -XX:SurvivorRatio=6 -XX:+AlwaysPreTouch
              -XX:+UseG1GC -XX:MaxGCPauseMillis=2000 -XX:GCTimeRatio=4 -XX:InitiatingHeapOccupancyPercent=30
              -XX:G1HeapRegionSize=8M -XX:ConcGCThreads=2 -XX:G1HeapWastePercent=10 -XX:+UseTLAB
              -XX:+ScavengeBeforeFullGC -XX:+DisableExplicitGC -Dcom.sun.management.jmxremote 
              -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false
               -Dcom.sun.management.jmxremote.port=49112 -Dcom.sun.management.jmxremote.rmi.port=49112 -Djava.rmi.server.hostname=ignite -Dcom.sun.management.jmxremote.ssl=false"
    volumes:
      - ./ignite/conf:/config
    ports:
     - "8085:8080"
     - "10802:10800"