version: '3.5'
services:
 zabbix-agent:
  build:
   context: ./agent2-systemd
   dockerfile: Dockerfile
  ports:
   - "10050:10050"
  volumes:
   - /sys/fs/cgroup:/sys/fs/cgroup:ro
  privileged: true
  networks:
   zabbix_54_default:
  stop_grace_period: 5s
networks:
  zabbix_54_default:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"