version: '2'
services:
  
  memcached-host:
    build:
      context: ./memcached
      dockerfile: Dockerfile
    command: ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisor.conf"]
    ports:
      - "11211:11211"
      - "10050:10050"
