version: "2"
services:
  zookeeper_1:
    image: bitnami/zookeeper:latest
    ports:
      # - "2181:2181"
      - "8890:8080"
    environment:
      # - JVMFLAGS=-Djava.rmi.server.hostname=zookeeper_1 -Dcom.sun.management.jmxremote.port=2099 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false

      # - ZOO_ENABLE_PROMETHEUS_METRICS=yes
      - ALLOW_ANONYMOUS_LOGIN=yes

      - ZOO_SERVER_ID=1
      - ZOO_SERVERS=0.0.0.0:2888:3888,zookeeper_2:2888:3888,zookeeper_3:2888:3888
  zookeeper_2:
    image: "bitnami/zookeeper:latest"
    ports:
      - "8891:8080"

    environment:
      - ZOO_SERVER_ID=2
      - ZOO_SERVERS=zookeeper_1:2888:3888,0.0.0.0:2888:3888,zookeeper_3:2888:3888
      # - ZOO_ENABLE_PROMETHEUS_METRICS=yes
      - ALLOW_ANONYMOUS_LOGIN=yes

  zookeeper_3:
    image: "bitnami/zookeeper:latest"
    ports:
      - "8892:8080"
    environment:
      - ZOO_SERVER_ID=3
      - ZOO_SERVERS=zookeeper_1:2888:3888,zookeeper_2:2888:3888,0.0.0.0:2888:3888

      - ZOO_ENABLE_PROMETHEUS_METRICS=yes
      - ALLOW_ANONYMOUS_LOGIN=yes


  kafka_1:
    image: bitnami/kafka:latest
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper_1:2181,zookeeper_2:2181,zookeeper_3:2181
      # - JVM_OPTS=-Djava.rmi.server.hostname=kafka_1
      # - LOCAL_JMX=no
      # - JMX_PORT=1099


  kafka_2:
    image: bitnami/kafka:latest
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper_1:2181,zookeeper_2:2181,zookeeper_3:2181
      # - JVM_OPTS=-Djava.rmi.server.hostname=kafka_2
      # - LOCAL_JMX=no
      # - JMX_PORT=1099


  kafka_3:
    image: bitnami/kafka:latest
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper_1:2181,zookeeper_2:2181,zookeeper_3:2181
      # - JVM_OPTS=-Djava.rmi.server.hostname=kafka_3
      # - LOCAL_JMX=no
      # - JMX_PORT=1099