version: '2'
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka1:
    image: bitnami/kafka:latest
    ports:
      - "9095:9092"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - JVM_OPTS=-Djava.rmi.server.hostname=kafka1
      - LOCAL_JMX=no
      - JMX_PORT=1099


  kafka2:
    image: bitnami/kafka:latest
    ports:
      - "9096:9092"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - JVM_OPTS=-Djava.rmi.server.hostname=kafka2
      - LOCAL_JMX=no
      - JMX_PORT=1099


  kafka3:
    image: bitnami/kafka:latest
    ports:
      - "9097:9092"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - JVM_OPTS=-Djava.rmi.server.hostname=kafka3
      - LOCAL_JMX=no
      - JMX_PORT=1099
